version: "3"

services:
  fllpostgres:
    image: fisherylogistics/fllpostgres:latest
    volumes:
      - "/data/postgres/pgdata:/var/lib/postgresql/data/pgdata"
      - "/data/postgres/backup:/mnt/backup"
    networks:
      - fllnet
    restart: always
    ports:
      - "127.0.0.1:5432:5432"

  couchdb:
    image: klaemo/couchdb:2.0.0
    volumes:
      - "/data/couchdb:/opt/couchdb/data"

  couchpost:
    image: fisherylogistics/couchpost:latest
    networks:
      - fllnet
    restart: always
    volumes:
      - "/data/logs/couchpost:/var/log/catchhub"

  fishserve_sender:
    image: fisherylogistics/fishserve-sender:latest
    networks:
      - fllnet
    restart: always
    volumes:
      - "/data/logs/fishserve-sender:/var/log/catchhub"
      - "/data/logs/fishserve-sender-supervisord:/var/log/supervisor"

  react_web_app:
    image: fisherylogistics/react-web-app:latest
    networks:
      - fllnet
    restart: always

  django_rest_api:
    image: fisherylogistics/rest-api:latest
    networks:
      - fllnet
    depends_on:
      - fllpostgres
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/data/letsencrypt/etc:/etc/nginx/certs"
      - "/data/letsencrypt/www:/var/www/letsencrypt"
      - "/data/logs/catchhub:/var/log/catchhub"
      - "/data/logs/nginx:/var/log/nginx"
      - "/data/logs/django-supervisord:/var/log/supervisor"
  
networks:
  fllnet:
