version: "3"

services:
  fllpostgres:
    image: fisherylogistics/fllpostgres:latest
    volumes:
      - "/data/postgres:/var/lib/postgresql/data/pgdata"
    networks:
      - fllnet
    restart: always
    ports:
      - "127.0.0.1:5432:5432"

  fluentd:
    image: fisherylogistics/fluentd
    volumes:
      - "/data/logs/fluentd:/fluentd/log"
    #ports: we probably don't need to expose ports to the host... unless we start logging docker container there
    #  - "24224:24224"
    #  - "24224:24224/udp"
    networks:
      - fllnet
    restart: always
      
  django_rest_api:
    image: fisherylogistics/rest-api:latest
    networks:
      - fllnet
    depends_on:
      - migration
      - fllpostgres
      - fluentd
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/data/letsencrypt/etc:/etc/nginx/certs"
      - "/data/letsencrypt/www:/var/www/letsencrypt"
  
  migration:
    image: fisherylogistics/rest-api:latest
    networks:
      - fllnet
    command: sh -c "cd /home/docker/code/app/ && python3 manage.py migrate --noinput"
    depends_on:
      - fllpostgres
      - fluentd

networks:
  fllnet:
