version: "3"

services:
  fllpostgres:
    image: fisherylogistics/fllpostgres:latest
    volumes:
      - "/data/postgres:/var/lib/postgresql/data/pgdata"
    networks:
      - fllnet
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
      
  django_rest_api:
    image: fisherylogistics/rest-api:latest
    networks:
      - fllnet
    depends_on:
      - migration
      - fllpostgres
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/data/letsencrypt/etc:/etc/nginx/certs"
      - "/data/letsencrypt/www:/var/www/letsencrypt"
      - "/data/logs/catchhub:/var/log/catchhub"
      - "/data/logs/nginx:/var/log/nginx"
      - "/data/logs/django-supervisord:/var/log/supervisor"
  
  migration:
    image: fisherylogistics/rest-api:latest
    networks:
      - fllnet
    command: sh -c "cd /home/docker/code/app/ && python3 manage.py migrate --noinput"
    depends_on:
      - fllpostgres

networks:
  fllnet:
