version: "3"

services:
  fllpostgres:
    image: fisherylogistics/fllpostgres:latest
    volumes:
      - "/data/postgres/pgdata:/var/lib/postgresql/data/pgdata"
      - "/data/postgres/backup:/mnt/backup"
    networks:
      - fllnet
    restart: always
    ports:
      - "127.0.0.1:5432:5432"

  couchdb:
    image: apache/couchdb:2.1
    volumes:
      - "/data/couchdb/data:/opt/couchdb/data"
      - "/data/couchdb/conf:/opt/couchdb/etc/local.d"
      - "/data/logs/couchdb:/opt/couchdb/var/log"

  couchpost:
    image: fisherylogistics/couchpost:latest
    networks:
      - fllnet
    restart: always
    volumes:
      - "/data/logs/couchpost:/var/log/catchhub"
      - "/data/logs/couchpost-supervisord:/var/log/supervisor"
    depends_on:
      - fllpostgres
      - couchdb

  fishserve_sender:
    image: fisherylogistics/fishserve-sender:latest
    networks:
      - fllnet
    restart: always
    volumes:
      - "/data/logs/fishserve-sender:/var/log/catchhub"
      - "/data/logs/fishserve-sender-supervisord:/var/log/supervisor"

  http_proxy:
    image: fisherylogistics/http-proxy:latest
    networks:
      - fllnet
    restart: always
    volumes:
      - "/data/letsencrypt/etc:/usr/local/openresty/nginx/conf/certs"
      - "/data/letsencrypt/www:/var/www/letsencrypt"
      # TODO logging
    ports:
      - "80:80"
      - "443:443"
  
  react_web_app:
    image: fisherylogistics/react-web-app:latest
    networks:
      - fllnet
    restart: always

  django_rest_api:
    image: fisherylogistics/rest-api:latest
    networks:
      - fllnet
    depends_on:
      - fllpostgres
    restart: always
    volumes:
      - "/data/logs/catchhub:/var/log/catchhub"
      - "/data/logs/nginx:/var/log/nginx"
      - "/data/logs/django-supervisord:/var/log/supervisor"
  
networks:
  fllnet:
